# Generated by Django 4.2.1 on 2023-05-29 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menufood_delete_coworker'),
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coworker',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_coworker', models.BooleanField(default=True, verbose_name='сотрудничающий представитель')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.franchise', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
            bases=('auths.customuser',),
        ),
    ]
