# Generated by Django 4.2.1 on 2023-06-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_franchise_image_alter_food_quantity'),
        ('auths', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('total_price', models.PositiveIntegerField(verbose_name='итоговая цена')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='заказчик')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food', verbose_name='заказанное блюдо')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-id'],
            },
        ),
    ]
