# Generated by Django 4.2.1 on 2023-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
