# Generated by Django 4.2.1 on 2023-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_rename_customer_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('payment', models.IntegerField(choices=[(1, 'Опата курьеру'), (2, 'Оплата картой')], default=1)),
                ('address', models.CharField(max_length=255, verbose_name='адрес доставки')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='оплачено ли'),
        ),
    ]
