# Generated by Django 4.2.1 on 2023-06-13 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_purchase_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 6, 2, 27, 194113, tzinfo=datetime.timezone.utc), verbose_name='дата и время создания'),
        ),
    ]
