# Generated by Django 4.2.1 on 2023-06-14 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_purchase_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 10, 15, 10, 657401, tzinfo=datetime.timezone.utc), null=True, verbose_name='время заказа'),
        ),
    ]
