# Generated by Django 4.2.1 on 2023-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_alter_order_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время заказа'),
        ),
    ]
