# Generated by Django 4.2.1 on 2023-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_order_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_number',
            field=models.CharField(max_length=16, null=True, verbose_name='номер карты'),
        ),
    ]
