# Generated by Django 4.2.1 on 2023-06-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0011_purchase_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='card_number',
        ),
    ]
