# Generated by Django 4.2.1 on 2023-06-15 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_franchise_image_alter_food_quantity'),
        ('auths', '0012_remove_purchase_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='franchise',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.franchise', verbose_name='франшиза'),
        ),
    ]
