# Generated by Django 4.2.1 on 2023-05-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.food', verbose_name='еда')),
                ('menuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu', verbose_name='меню')),
            ],
        ),
        migrations.DeleteModel(
            name='Coworker',
        ),
    ]
