# Generated by Django 4.2.1 on 2023-05-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menufood_delete_coworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menufood',
            name='foodID',
        ),
        migrations.RemoveField(
            model_name='menufood',
            name='menuID',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='food',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.franchise', verbose_name='франшиза'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuFood',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
