# Generated by Django 4.2.1 on 2023-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_food_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
