# Generated by Django 4.2.1 on 2023-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_food_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-id'], 'verbose_name': 'блюдо', 'verbose_name_plural': 'блюда'},
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=25, verbose_name='количество еды'),
        ),
    ]
