# Generated by Django 4.2.1 on 2023-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_food_options_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=25, null=True, verbose_name='количество еды'),
        ),
    ]
