# Generated by Django 4.2.1 on 2023-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_franchise_image_alter_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cluster',
            field=models.PositiveIntegerField(null=True, verbose_name='кластер'),
        ),
    ]
